#first create the database
create database covidinfo;
use covidinfo;

#now add tables
create table deaths(
	iso_code varchar(8),
	continent varchar(13),
    location varchar(32),
    date varchar(10),
    population bigint unsigned,
    population_density float check (population_density>=0),
    total_cases int unsigned,
    new_cases int unsigned,
    new_cases_smoothed float check(new_cases_smoothed>=0),
    total_deaths mediumint unsigned,
    new_deaths smallint unsigned,
    new_deaths_smoothed float check(new_deaths_smoothed>=0),
    total_cases_per_million float check(total_cases_per_million>=0),
    new_cases_per_million float check(new_cases_per_million>=0),
    new_cases_smoothed_per_million float check(new_cases_smoothed_per_million>=0),
    total_deaths_per_million float check(total_deaths_per_million>=0),
    new_deaths_per_million float check(new_deaths_per_million>=0),
    new_deaths_smoothed_per_million float check(new_deaths_smoothed_per_million>=0),
    reproduction_rate float,
    icu_patiens smallint,
    icu_patiens_per_million float check(icu_patiens_per_million>=0),
    hosp_patients mediumint unsigned,
    hosp_patients_per_million float check(hosp_patients_per_million>=0),
    weekly_icu_admissions smallint unsigned,
    weekly_icu_admissions_per_million float check(weekly_icu_admissions_per_million>=0),
    weekly_hosp_admissions mediumint unsigned,
    weekly_hosp_admissions_per_million float check(weekly_hosp_admissions_per_million>=0)
);

####the date column must be set to varchar in order to import large amounts of data###
####I haven't found a straight way to import data from a csv file and converted to date

create table vaccines(
	iso_code varchar(8),
	continent varchar(13),
    location varchar(32),
    date varchar(10),
    total_tests int unsigned,
    new_tests mediumint unsigned,
    total_tests_per_thousand float check(total_tests_per_thousand>=0),
    new_tests_per_thousand float check(new_tests_per_thousand>=0),
    new_tests_smoothed mediumint unsigned,
    new_tests_smoothed_per_thousand float check(new_tests_smoothed_per_thousand>=0),
    positive_rate float check(positive_rate>=0),
    tests_per_case mediumint unsigned,
    tests_units enum('people tested','samples tested','tests performed','units unclear'),
    total_vaccinations bigint unsigned,
    people_vaccinated bigint unsigned,
    people_fully_vaccinated bigint unsigned,
    total_boosters bigint unsigned,
    new_vaccinations int unsigned,
    new_vaccinations_smoothed int unsigned,
    total_vaccinations_per_hundred float check(total_vaccinations_per_hundred>=0),
    people_vaccinated_per_hundred float check(people_vaccinated_per_hundred>=0),
    people_fully_vaccinated_per_hundred float check(people_fully_vaccinated_per_hundred>=0),
    total_boosters_per_hundred float check(total_boosters_per_hundred>=0),
    new_vaccinations_smoothed_per_million mediumint unsigned,
    new_people_vaccinated_smoothed int unsigned,
    new_people_vaccinated_smoothed_per_hundred int unsigned,
	stringency_index float check(stringency_index>=0),
    population_density float check(population_density>=0),
    median_age float check(median_age>=0),
    aged_65_older float check(aged_65_older>=0),
    aged_70_older float check(aged_70_older>=0),
    gdp_per_capita float check(gdp_per_capita>=0),
	extreme_poverty float check(extreme_poverty>=0),
    cardiovasc_death_rate float check(cardiovasc_death_rate>=0),
    diabetes_prevelance float check(diabetes_prevelance>=0),
    female_smokers float check(female_smokers>=0),
    male_smokers float check(male_smokers>=0),
    handwashing_facilities float check(handwashing_facilities>=0),
    hospital_beds_per_thousand float check(hospital_beds_per_thousand>=0),
    life_expectancy float check(life_expectancy>=0),
    human_development_index float check(human_development_index>=0),
    excess_mortality_cumulative_absolute float,
    excess_mortality_cumulative float,
    excess_mortality_cumulative_per_million float,
    excess_mortality float
);
